apiVersion: v1
kind: Secret
metadata:
    name: garage
stringData:
    GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:MvgJuATiHmbT5YoiZYqS/oKSeuTB1YmjZTO1eb/wLttepJUEuNntial2+Q==,iv:4dHMTq5DBYKnt6rki6NENEtmDufzJV5rEdK3vDluOQc=,tag:WmC2308cvsD7GPPWJFWzeQ==,type:str]
    GARAGE_METRICS_TOKEN: ENC[AES256_GCM,data:2EU0a8debBGVqEol4QoH6w4ifxQzTvOnbe0XgpNHHxnjzj9zmmhxbhatW2dc6OC5,iv:b+98aeAz0TXLK+6lreQZoGtgzQfhpnvAfAHEyD1+UFs=,tag:ywFFVDlZyUwyCLWFhoGUxQ==,type:str]
    GARAGE_RPC_SECRET: ENC[AES256_GCM,data:EAjppBVd9JYMQLHyKjSTGredCkWAtUvfGW2G/wEdo4XxVJBNqndz60ON0RYWAQEuFOD1uVohznvyWtX0U4+mug==,iv:Fl0rYa5orU5N13p/uvdy9zWS8ArZeGqG8YKaybNAJYU=,tag:zKQ5015Ekb4fnIDQB1EprA==,type:str]
sops:
    age:
        - recipient: age1en4cf0wprkkt486yz5v68ee2duqsfj2w064x27dk0mnnxse8gs7q47fznp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySWpoSEtwb1phYUtCSk1i
            bFBmUjdDVk5kSGpacXk4dWg2NGxTQ2o1UmxRCk1xRDZMeVhtQklPbmhpanl5SDhP
            bUlWT1ozaDBuYytjeFdOSEpMRFVUczgKLS0tIDYyQWtkcndKVVo2VXFEQ2dMM01w
            bFpqU2V3bXFQRWVQelg4TTA5RGtzMFkKJu0woPvI2VSlPqN4tne+rcPFzj3iQfwM
            5UwRVbvcepzGUwymCDt0ZO1FpRhdjqUJuTKqUc9S2/zuRYKuN97wEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T15:39:41Z"
    mac: ENC[AES256_GCM,data:cjqO/w4ftoiHkzarS3f+IuslOhyf8aXp/rksbJ/xPmLDoTU+RBT3ZTrRx8k73FXXcEXy+OIWWitkYoAPyjugOysia/Wi4y6Sb7x+ctRQ07+8WsZuLipM1JzjlyuXJSyidmCLhzVsbpOvqCRphJaAFc4KRI2+yCMYWzp4dvkQ/Ys=,iv:i+qLgG0kIQgBn/K7Egb/deKojXgY9EcMJAD+MdeSQXs=,tag:8cj64+JcaD1peryDa4AbCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
