# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-secret
type: Opaque
stringData:
    KOPIA_FS_PATH: ENC[AES256_GCM,data:WwJolyCc0T7hJ/g=,iv:84rwrc7u5ZCz3iOCOA05hkDMKUIBsA6MvP2MP48gxiQ=,tag:atLbAaWA+vnOvi9Cc5fCng==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:0BItXVGvLki9eg==,iv:aS+cPTtCV5U1Q4qQtnOVWcwN3O3KXGPjckwArqWPOgk=,tag:9SJCSNl55wZ7UmjxzGMtkg==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:zO36gBs5WGLVcShPrg8sillfCg4qiA==,iv:KetTZGVN3vTT+LsAdqm+wRSjyO7FVPTyCghvpll7dPE=,tag:LP9uEd+3m7LDK2ytJx7qpQ==,type:str]
sops:
    age:
        - recipient: age1en4cf0wprkkt486yz5v68ee2duqsfj2w064x27dk0mnnxse8gs7q47fznp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOC9UU2xVTERLUkxTc3c4
            cHdrUDRWR3F2NUV2NXMxMUxwNytTRnNyQ0JjCjZFYnFXcGxTTm5aVkt3aWh0YjZ5
            dXR4dUptZiswNXVJU3dpOUhGVHJsV2sKLS0tIGE1R2F1WDQ3ZmhYcE5URTNWc2ZP
            UUx4eTBwakltY3VNMzR2MkNlaDFCUVUKvzB7r5FaYhO25hdfK03xdPoUTwZ1jakM
            PYYHLjhTxBYRQ33QqkwYyu8Cc+W0WBbF0WFym+fTWAs9OM9rZZ+5Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T17:21:33Z"
    mac: ENC[AES256_GCM,data:b96p0vDN9qjzjtSjOWR3hbWG56WbHLXb1wI++Oi6HB1M50MddPx5MXDgYvYJDcCjHXJs83ghRDb4q7zI6Sy32UaNT8UTPjE0LeE000btHsKpAwDXqXIvO1jvX2QL6vJW4eStxcYugsV06qGMH1wwvbXrmuwnK+apvkCpi5CDduE=,iv:W0d8LNsSyMwTbXlwJN3wO87STpesc1g8frPn5kKNprc=,tag:r4cfs/tAAq7eziT60G/ihw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
