# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: volsync-maintenance-secret
type: Opaque
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:bjEdbTbcvVFCtA==,iv:SQ6ObosHpTUYYJcrxkwkqMn0J1OBCcgVAAVUNlPUw3g=,tag:TJT8o1YIMw36yP5PbOv3mQ==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:ihvgckOBI8msyCfmkYu7RM9cTR2MxQ==,iv:Bkh3cagaCSN+KS+eKoSpAVhlJ1KtcWm5Zpi6S9iy3KU=,tag:DuYHuYvIF8sSYE8BA9wcdg==,type:str]
sops:
    age:
        - recipient: age1en4cf0wprkkt486yz5v68ee2duqsfj2w064x27dk0mnnxse8gs7q47fznp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTDNISk41Q0ptbEJaWkgr
            b3BOZXk4bDJYa3ZLV2pWSU8wREVwejBVTW5NCkRvTzl6VVE2VWl4V3RHZ213a2x4
            RWFKdkczeFNoY2tFL1hXZUFDbXcyNU0KLS0tIEZkQnRDMEQwR1NybjNYRU1NcXVY
            T3hJZ3c0ZnZtaGdybmorL2VBRFVZWXcKZOKgw5r+ySxcCy8HXS+OieU65gExEqt4
            peDC//wGVAfbv0h0feIqAx2n0MynKTopO5nsS1k2aPy+iyrSJ2lCjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T17:29:43Z"
    mac: ENC[AES256_GCM,data:/ehd0O8TSwEN83A7dw1yUPDUEXGTiMwP0LtTS01xcmyBrED2loMJIFwbXBTW4WQI4oamM8cZQ8Rrq5nSR6d1HrSbRmPEdWpLAM/0gYQpV2hX9b+P1VL1owYl45StNK0Fq8U22N0Prke8Rgp+8EDZUErzcRc3Wqkt5Gm/lOfnZSg=,iv:2MTU5RZS10SXVdshXprsoQjCi0hnx/CmU9pUALwCths=,tag:I7BJDEIDxgsJYv7OBO/9gQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
