# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: volsync-maintenance-secret
type: Opaque
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:bjEdbTbcvVFCtA==,iv:SQ6ObosHpTUYYJcrxkwkqMn0J1OBCcgVAAVUNlPUw3g=,tag:TJT8o1YIMw36yP5PbOv3mQ==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:eOyoOUsb+a/3TP94ov0paGy8AEvQcRPp,iv:pck9RvHK5fHbe+QomC+ruTxbfKYgc5yQEEXvb3F8qP0=,tag:ajt2IicejHKIE+3k+/u/cQ==,type:str]
sops:
    age:
        - recipient: age1en4cf0wprkkt486yz5v68ee2duqsfj2w064x27dk0mnnxse8gs7q47fznp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTDNISk41Q0ptbEJaWkgr
            b3BOZXk4bDJYa3ZLV2pWSU8wREVwejBVTW5NCkRvTzl6VVE2VWl4V3RHZ213a2x4
            RWFKdkczeFNoY2tFL1hXZUFDbXcyNU0KLS0tIEZkQnRDMEQwR1NybjNYRU1NcXVY
            T3hJZ3c0ZnZtaGdybmorL2VBRFVZWXcKZOKgw5r+ySxcCy8HXS+OieU65gExEqt4
            peDC//wGVAfbv0h0feIqAx2n0MynKTopO5nsS1k2aPy+iyrSJ2lCjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T15:41:45Z"
    mac: ENC[AES256_GCM,data:+/rvtc5jammbZcv/9/dkSoNi1YpU6CjCSuNZs70tyyWMupeRjdIrN73JZ/QEdv1qfKlZqHMHZRWETVrHUNaC4WNZ69U0KJQyVDu8Dfj00ndSzTkaYqsxb8gde764x6wEgxRrWlTTA4x8g8UBicjUFsshINIo82Uif0FueU/rL/Y=,iv:ObkoCaSdnl1WPlIFhFF5xXM2cqPY/wQfbxiMyVWHbhY=,tag:B4qfISqVl5/1KilnipJztg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
