# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.0.6.10:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.0.6.10"
additionalMachineCertSans: *sans

clusterPodNets: ["172.30.0.0/16"]
clusterSvcNets: ["172.31.0.0/16"]

cniConfig:
  name: none

nodes:
  - hostname: "singlenodemaster"
    ipAddress: "10.0.6.211"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: true

    networkInterfaces:
      # Stable parent interface just like onedr0p
      - interface: bond0
        bond:
          mode: active-backup
          deviceSelectors:
            - hardwareAddr: "bc:24:11:02:2d:02"

        mtu: 1500

        # Native VLAN 6 (untagged)
        dhcp: false
        addresses:
          - 10.0.6.211/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.6.1

        vip:
          ip: 10.0.6.10

        # Tagged VLAN 56 for Multus/macvlan
        # Add dummy link-local address to keep interface up for macvlan
        vlans:
          - vlanId: 56
            dhcp: false
            mtu: 1500
            addresses:
              - 169.254.1.1/32

# Global patches applied after Talhelper rendering
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"
